version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - mongo
    image: cerometros-web
    restart: on-failure
    env_file: docker.env
    ports:
      - 80:80
    networks:
      - cerometros-net
  
  mongo:
    container_name: mongo
    command:
      - --storageEngine=wiredTiger
    image: mongo:4.2.5-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGOINITDB_ROOT_USERNAME: root
      MONGOINITDB_ROOT_PASSWORD: CeroM3tros$
    volumes:
      - $PWD/data:/data/db
      - $PWD/database:/opt/database
    networks:
      - cerometros-net

networks:
      - cerometros-net
