version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - mongo
    image: cerometros-web
    restart: on-failure
    env_file: docker.env
    ports:
      - 80:80
    networks:
      - cerometros-net
  
  ssl-proxy:
    container_name: ssl-proxy
    image: justsml/ssl-proxy:latest
    environment:
    - HTTP_PORT=443
    - SERVER_NAME=cerometros.dimemex.site
    - UPSTREAM_TARGET=app:80
    - CERT_PUBLIC_PATH=/certs/fullchain.pem
    - CERT_PRIVATE_PATH=/certs/privkey.pem
    volumes:
    - /certs:/certs:ro
    depends_on:
      - app
    ports:
      - 443:443
    networks:
      - cerometros-net
  
  mongo:
    container_name: mongo
    command:
      - --storageEngine=wiredTiger
    image: mongo:4.2.5-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CeroM3tros
    volumes:
      - $PWD/data:/data/db
      - $PWD/database/zmeters:/opt/database
    networks:
      - cerometros-net

  crontab:
    container_name: crontab
    build: 
      context: .
      dockerfile: cron-dockerfile
      image: crontab
      privileged: : true
      depends_on: 
        mongo
      volumes: 
        - ./backups:/opt/backups
      networks:
      - cerometros-net 

networks:
      cerometros-net:
